apiVersion: v1
kind: Secret
metadata:
  name: ai-resume-secrets
  namespace: ai-resume
type: Opaque
stringData:
  POSTGRES_DB: "resume_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  JWT_SECRET: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  ADMIN_PASSWORD: "anwartamasna"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-resume-config
  namespace: ai-resume
data:
  # Spring Boot Backend configs
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.ai-resume.svc.cluster.local:5432/resume_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  MINIO_URL: "http://minio.ai-resume.svc.cluster.local:9000"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.ai-resume.svc.cluster.local:9092"
  
  # Python OCR & NLP Service configs
  KAFKA_BOOTSTRAP_SERVERS: "kafka.ai-resume.svc.cluster.local:9092"
  KAFKA_REQUEST_TOPIC: "resume-analysis-request"
  KAFKA_RESPONSE_TOPIC: "resume-analysis-response"
  MINIO_ENDPOINT: "minio.ai-resume.svc.cluster.local:9000"
  OLLAMA_HOST: "http://ollama.ai-resume.svc.cluster.local:11434"
  OLLAMA_MODEL: "qwen2.5:1.5b"
